Resources:
  RewardsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: reward_id
          AttributeType: S
      KeySchema:
        - AttributeName: reward_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
